import type { Metadata } from "next";
import { Lexend } from "next/font/google";

import { cn } from "@/utils";

import "./globals.css";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-[#F4F4F4]", "relative", lexend.className)}>
        {children}
      </body>
    </html>
  );
}
